version: '3.9'
services:
  aerospike:
    build: .
    platform: linux/amd64
    restart: always
    container_name: aerospike
    ports:
      - '3000-3002:3000-3002'
    volumes:
      - aerospike-data:/opt/aerospike/data
      - aerospike-config:/etc/aerospike
volumes:
  aerospike-data:
  aerospike-config:
